; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.15 on Sat Jan 07 2023 21:50:31 GMT-0500 (Eastern Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


