; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.15 on Sat Jan 07 2023 21:50:32 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P1

